steps:
- script: dotnet restore -v minimal src/Pootis-Bot.sln
  displayName: Restore Packages

- script: dotnet build src/Pootis-Bot.sln --no-restore -v minimal -c $(buildConfiguration) --framework $(framework)
  displayName: Build Project