steps:
- task: UseDotNet@2
  displayName: 'Setup .NET 5'
  inputs:
    packageType: sdk
    version: 5.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore -v minimal src/Pootis-Bot.sln
  displayName: Restore Packages

- script: dotnet build src/Pootis-Bot.sln --no-restore -v minimal -c $(buildConfiguration) --framework $(framework)
  displayName: Build Project