steps:
- script: dotnet restore -v minimal Pootis-Bot.sln
  displayName: Restore Packages

- script: dotnet build Pootis-Bot.sln --no-restore --framework netcoreapp3.0 -v minimal -c $(buildConfiguration)
  displayName: Build Projects