trigger:
- master

variables:
  buildConfiguration: 'Release'
  framework: 'netcoreapp3.0'

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: azure/build.yml

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: azure/build.yml
